name: dapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  web_socket_channel: ^2.4.0

dependency_overrides:
  web3dart: ^2.7.2
  stream_channel: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - build/contracts/HelloWorld.json
